### ISSUE TITLE
Build Maker UI

### ISSUE THREAD

**Issue by lbuttorff** [dbd-projects/dbd-apps-ui#1]
## Description
This story is for making a page on the UI that allows selection of the build type (based on the 5 build archetypes) and shows a page with the generated results.

## Tasks

- [ ] Make a Selection UI for the build type
- [ ] Make endpoints for selection UI (GET & POST)
- [ ] Make a Build View UI for seeing the generated Build
- [ ] Make GET endpoint for the Build View UI
- [ ] Add unit tests for all code described above
